FROM public.ecr.aws/lambda/python:3.10
RUN pip install poetry==1.5
COPY poetry.lock pyproject.toml main.py ${LAMBDA_TASK_ROOT}/
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root
WORKDIR ${LAMBDA_TASK_ROOT}/
CMD [ "main.handler" ]