name: Deployment

on:
  push:
    branches: ["tests"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install poetry
        run: python -m pip install poetry==1.5

      - name: Configure poetry
        run: python -m poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: python -m poetry install

      - name: Run tests
        run: poetry run pytest && poetry run mypy .
