name: Deployment

on:
  push:
    branches: ["tests"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install poetry
        run: python -m pip install poetry==1.5

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: python -m poetry install --no-interaction --no-ansi --no-root

      - name: Run tests
        run: poetry run pytest && poetry run mypy fluxional/

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Install dependencies
        run: npm install -g aws-cdk

      - name: Synth stack
        working-directory: stack/
        run: cdk synth
        env:
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
